# -*- coding: utf-8 -*-
"""MACROPULSE WEEKLY

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13zQglDnlqXFE7yRdAWPJnah3UO3UCnQ-
"""

import pandas as pd

url = "https://stats.oecd.org/SDMX-JSON/data/WSCMKT/A.GLOBAL.SALES.A/all?contentType=csv"
semi = pd.read_csv(url)
semi.head()

!pip install yfinance
import yfinance as yf
import pandas as pd
import plotly.graph_objects as go

sox = yf.download("^SOX", start="2010-01-01", end="2026-12-31")

sox = sox[['Close']].rename(columns={'Close': 'SOX'})
sox['observation_date'] = sox.index

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv(list(uploaded.keys())[0])
df['observation_date'] = pd.to_datetime(df['observation_date'])

df_merged = pd.merge(
    df,
    sox[['observation_date', 'SOX']],
    on='observation_date',
    how='left'
)

# Flatten multi-index columns if needed
if isinstance(sox.columns, pd.MultiIndex):
    sox.columns = ['_'.join([str(c) for c in col if c]).strip() for col in sox.columns]

sox = sox.rename(columns={'Close_^SOX': 'SOX'})

sox.columns

sox['observation_date'] = sox.index

df_merged = pd.merge(
    df,
    sox[['observation_date', 'SOX']],
    on='observation_date',
    how='left'
)

sox.columns

sox = sox.rename(columns={'SOX_^SOX': 'SOX'})

df_merged = pd.merge(
    df,
    sox[['observation_date', 'SOX']],
    on='observation_date',
    how='left'
)

zoom = df_merged[
    (df_merged['observation_date'] >= "2022-01-01") &
    (df_merged['observation_date'] <= "2026-12-31")
]

import plotly.graph_objects as go

fig = go.Figure()

# Bitcoin (left axis)
fig.add_trace(go.Scatter(
    x=zoom['observation_date'],
    y=zoom['CBBTCUSD'],
    name='Bitcoin Price (USD)',
    line=dict(color='royalblue', width=2)
))

# SOX (right axis)
fig.add_trace(go.Scatter(
    x=zoom['observation_date'],
    y=zoom['SOX'],
    name='SOX Index',
    line=dict(color='firebrick', width=3, dash='dot'),
    yaxis='y2'
))

fig.update_layout(
    title="Bitcoin Price vs SOX Semiconductor Index (2022–2026)",
    xaxis=dict(title="Date"),
    yaxis=dict(title="Bitcoin Price (USD)"),
    yaxis2=dict(
        title="SOX Index",
        overlaying='y',
        side='right'
    ),
    template="plotly_white",
    legend=dict(x=0.01, y=0.99)
)

fig.show()

fig.update_layout(
    title="Bitcoin Price vs SOX Semiconductor Index (2022–2026)",
    xaxis=dict(title="Date"),
    yaxis=dict(title="Bitcoin Price (USD)"),
    yaxis2=dict(
        title="SOX Index",
        overlaying='y',
        side='right'
    ),
    template="plotly_white",
    legend=dict(
        x=0.02,   # move slightly inward from the left
        y=0.98,   # move slightly down from the top
        bgcolor="rgba(255,255,255,0.7)"  # optional: makes it readable
    ),
    margin=dict(
        l=60,  # left
        r=60,  # right
        t=80,  # top
        b=40   # bottom
    )
)

import yfinance as yf
import pandas as pd

tnx = yf.download("^TNX", start="2010-01-01", end="2026-12-31")
tnx = tnx[['Close']].rename(columns={'Close': 'TNX'})
tnx['TNX'] = tnx['TNX'] / 100  # convert from percent*100 to percent
tnx['observation_date'] = tnx.index

cpi = yf.download("CPIAUCSL", start="2010-01-01", end="2026-12-31")
cpi = cpi[['Close']].rename(columns={'Close': 'CPI'})
cpi['observation_date'] = cpi.index

cpi['CPI_YoY'] = cpi['CPI'].pct_change(12)

real = pd.merge(
    tnx[['observation_date', 'TNX']],
    cpi[['observation_date', 'CPI_YoY']],
    on='observation_date',
    how='left'
)

real['Real_Yield'] = real['TNX'] - real['CPI_YoY']

tnx.columns

cpi.columns

# Flatten TNX columns
tnx.columns = ['_'.join([str(c) for c in col if c]).strip() for col in tnx.columns]

# Flatten CPI columns
cpi.columns = ['_'.join([str(c) for c in col if c]).strip() for col in cpi.columns]

tnx = tnx.rename(columns={'TNX_^TNX': 'TNX'})
cpi = cpi.rename(columns={'CPI_CPIAUCSL': 'CPI'})

real = pd.merge(
    tnx[['observation_date', 'TNX']],
    cpi[['observation_date', 'CPI_YoY']],
    on='observation_date',
    how='left'
)

real['Real_Yield'] = real['TNX'] - real['CPI_YoY']
real['Real_Yield_90d'] = real['Real_Yield'].rolling(90).mean()
real['Real_Yield_Inverted'] = -real['Real_Yield_90d']

fig.update_layout(
    title={
        "text": "Bitcoin vs Inverted Real U.S. Treasury Yields<br><sup>BTC thrives when real yields fall — the true 'cost of money' signal</sup>",
        "x": 0.5
    },
    ...
)

fig.update_layout(
    title={
        "text": "Bitcoin vs Inverted Real U.S. Treasury Yields<br><sup>BTC thrives when real yields fall — the true cost of money signal</sup>",
        "x": 0.5
    },
    xaxis=dict(title="Date"),
    yaxis=dict(title="Bitcoin Price (USD)"),
    yaxis2=dict(
        title="Inverted Real Yield",
        overlaying='y',
        side='right'
    ),
    template="plotly_white",
    legend=dict(x=0.02, y=0.98),
    margin=dict(l=60, r=60, t=80, b=40)
)

import yfinance as yf

nq = yf.download("^NDX", start="2010-01-01", end="2026-12-31")
nq = nq[['Close']].rename(columns={'Close': 'NQ'})
nq['observation_date'] = nq.index

df_nq = pd.merge(
    df,  # your BTC dataframe
    nq[['observation_date', 'NQ']],
    on='observation_date',
    how='left'
)

nq.columns

nq.columns = ['_'.join([str(c) for c in col if c]).strip() for col in nq.columns]

nq = nq.rename(columns={'Close_^NDX': 'NQ'})

nq['observation_date'] = nq.index

df_nq = pd.merge(
    df,
    nq[['observation_date', 'NQ']],
    on='observation_date',
    how='left'
)

nq.columns

nq.columns = ['_'.join([str(c) for c in col if c]).strip() for col in nq.columns]

nq = nq.rename(columns={'Close_^NDX': 'NQ'})

nq['observation_date'] = nq.index

df_nq = pd.merge(
    df,
    nq[['observation_date', 'NQ']],
    on='observation_date',
    how='left'
)

nq.columns

nq = nq.rename(columns={'NQ__^NDX': 'NQ'})

nq = nq.drop(columns=['o_b_s_e_r_v_a_t_i_o_n__d_a_t_e'])

nq = nq.drop(columns=['o_b_s_e_r_v_a_t_i_o_n__d_a_t_e'])

nq = nq.drop(columns=['o_b_s_e_r_v_a_t_i_o_n__d_a_t_e'])

nq = nq.rename(columns={'NQ__^NDX': 'NQ'})

nq.columns

df_nq = pd.merge(
    df,
    nq[['observation_date', 'NQ']],
    on='observation_date',
    how='left'
)

nq.columns

nq = nq.rename(columns={'N_Q__^N_D_X': 'NQ'})

nq.columns

nq = nq.drop(columns=['o_b_s_e_r_v_a_t_i_o_n___d_a_t_e'])

nq.columns

nq = nq.rename(columns={'N_Q___^_N_D_X': 'NQ'})
df_nq = pd.merge(
    df,
    nq[['observation_date', 'NQ']],
    on='observation_date',
    how='left'
)

# Merge the 'NQ' column from df_nq into 'zoom'
zoom = pd.merge(zoom, df_nq[['observation_date', 'NQ']], on='observation_date', how='left')

zoom['BTC_norm'] = zoom['CBBTCUSD'] / zoom['CBBTCUSD'].iloc[0] * 100
zoom['NQ_norm'] = zoom['NQ'] / zoom['NQ'].iloc[0] * 100

zoom['BTC_NQ_ratio'] = zoom['CBBTCUSD'] / zoom['NQ']

halvings = [
    "2012-11-28",
    "2016-07-09",
    "2020-05-11",
    "2024-04-20"
]

for h in halvings:
    fig.add_vline(
        x=pd.to_datetime(h).to_pydatetime(), # Convert to Python datetime object
        line=dict(color="black", width=1, dash="dot"),
        opacity=0.6
    )

walcl = yf.download("WALCL", start="2010-01-01", end="2026-12-31")
walcl = walcl[['Close']].rename(columns={'Close': 'Fed_Balance'})
walcl['observation_date'] = walcl.index

# Flatten walcl columns if they are MultiIndex
if isinstance(walcl.columns, pd.MultiIndex):
    walcl.columns = ['_'.join([str(c) for c in col if c]).strip() for col in walcl.columns]
    # Rename the specific column that corresponds to Fed_Balance
    if 'Fed_Balance_WALCL' in walcl.columns:
        walcl = walcl.rename(columns={'Fed_Balance_WALCL': 'Fed_Balance'})

df_liq = pd.merge(
    df_nq,  # your BTC+NQ merged dataframe
    walcl[['observation_date', 'Fed_Balance']],
    on='observation_date',
    how='left'
)

# Merge Fed_Balance into zoom before plotting
zoom = pd.merge(zoom, df_liq[['observation_date', 'Fed_Balance']], on='observation_date', how='left')

fig.add_trace(go.Scatter(
    x=zoom['observation_date'],
    y=zoom['Fed_Balance'],
    name='Fed Balance Sheet',
    line=dict(color='green', width=2, dash='dash'),
    yaxis='y2'
))

import plotly.graph_objects as go

fig = go.Figure()

# Bitcoin (left axis)
fig.add_trace(go.Scatter(
    x=zoom['observation_date'],
    y=zoom['CBBTCUSD'],
    name='Bitcoin Price (USD)',
    line=dict(color='royalblue', width=2)
))

# Nasdaq-100 (right axis)
fig.add_trace(go.Scatter(
    x=zoom['observation_date'],
    y=zoom['NQ'],
    name='Nasdaq-100 Index (NQ)',
    line=dict(color='firebrick', width=3, dash='dot'),
    yaxis='y2'
))

# Halving markers
halvings = [
    "2012-11-28",
    "2016-07-09",
    "2020-05-11",
    "2024-04-20"
]

for h in halvings:
    fig.add_vline(
        x=pd.to_datetime(h).to_pydatetime(), # Convert to Python datetime object
        line=dict(color="black", width=1, dash="dot"),
        opacity=0.6
    )

fig.update_layout(
    title={
        "text": "Bitcoin vs Nasdaq‑100 (NQ)<br><sup>BTC behaves like high‑beta liquidity‑sensitive tech</sup>",
        "x": 0.5
    },
    xaxis=dict(title="Date"),
    yaxis=dict(title="Bitcoin Price (USD)"),
    yaxis2=dict(
        title="Nasdaq‑100 Index",
        overlaying='y',
        side='right'
    ),
    template="plotly_white",
    legend=dict(x=0.02, y=0.98),
    margin=dict(l=60, r=60, t=80, b=40)
)

fig.show()

import plotly.graph_objects as go

fig = go.Figure()

# Bitcoin (left axis)
fig.add_trace(go.Scatter(
    x=zoom['observation_date'],
    y=zoom['CBBTCUSD'],
    name='Bitcoin Price (USD)',
    line=dict(color='royalblue', width=2)
))

# Nasdaq-100 (right axis)
fig.add_trace(go.Scatter(
    x=zoom['observation_date'],
    y=zoom['NQ'],
    name='Nasdaq-100 Index (NQ)',
    line=dict(color='firebrick', width=3, dash='dot'),
    yaxis='y2'
))

# Halving markers
halvings = [
    "2012-11-28",
    "2016-07-09",
    "2020-05-11",
    "2024-04-20"
]

for h in halvings:
    fig.add_vline(
        x=pd.to_datetime(h).to_pydatetime(), # Convert to Python datetime object
        line=dict(color="black", width=1, dash="dot"),
        opacity=0.6
    )

fig.update_layout(
    title={
        "text": "Bitcoin vs Nasdaq‑100 (NQ), 2022–2026<br><sup>BTC behaves like high‑beta liquidity‑sensitive tech</sup>",
        "x": 0.5
    },
    xaxis=dict(title="Date", range=["2022-01-01", "2026-12-31"]),
    yaxis=dict(title="Bitcoin Price (USD)"),
    yaxis2=dict(
        title="Nasdaq‑100 Index",
        overlaying='y',
        side='right'
    ),
    template="plotly_white",
    legend=dict(x=0.02, y=0.98),
    margin=dict(l=60, r=60, t=80, b=40)
)

fig.show()

fig.add_trace(go.Scatter(
    x=zoom['observation_date'],
    y=zoom['Fed_Balance'],
    name='Fed Balance Sheet',
    line=dict(color='green', width=2, dash='dash'),
    yaxis='y3' # Use a new y-axis for Fed Balance Sheet
))

fig.update_layout(
    yaxis3=dict(
        title='Fed Balance Sheet',
        overlaying='y',
        side='right',
        anchor='x',
        position=1 # Position to the right of y2
    )
)

fig.show()

!pip install pytrends

from pytrends.request import TrendReq
import pandas as pd

pytrends = TrendReq(hl='en-US', tz=0)

pytrends.build_payload(
    kw_list=['AI'],
    timeframe='2022-01-01 2026-12-31',
    geo=''
)

gt = pytrends.interest_over_time().reset_index()
gt = gt.rename(columns={'date': 'observation_date', 'AI': 'AI_Searches'})
gt = gt[['observation_date', 'AI_Searches']]

df_ai = pd.merge(
    df,
    gt,
    on='observation_date',
    how='left'
)

# Commented out IPython magic to ensure Python compatibility.
# %whos DataFrame

import yfinance as yf
import pandas as pd

btc = yf.download("BTC-USD", start="2010-01-01", end="2026-12-31")

# Flatten MultiIndex columns, if any
btc.columns = ['_'.join(col).strip() if isinstance(col, tuple) else col for col in btc.columns.values]

# Now select and rename the 'Close' column
btc = btc[['Close_BTC-USD']].rename(columns={'Close_BTC-USD': 'CBBTCUSD'})
btc['observation_date'] = btc.index

df = btc.reset_index(drop=True)

# Commented out IPython magic to ensure Python compatibility.
# %whos DataFrame

df_ai = pd.merge(
    df,
    gt,
    on='observation_date',
    how='left'
)

df = df.reset_index()

df = df.rename(columns={'Date': 'observation_date'})

df.columns
gt.columns

gt = gt.rename(columns={'date': 'observation_date'})

df_ai = pd.merge(
    df,
    gt,
    on='observation_date',
    how='left'
)

df_ai = pd.merge(
    df,
    gt,
    on='observation_date',
    how='left'
)

zoom = df_ai[
    (df_ai['observation_date'] >= "2022-01-01") &
    (df_ai['observation_date'] <= "2026-12-31")
]

import plotly.graph_objects as go

fig = go.Figure()

# Bitcoin (left axis)
fig.add_trace(go.Scatter(
    x=zoom['observation_date'],
    y=zoom['CBBTCUSD'],
    name='Bitcoin Price (USD)',
    line=dict(color='royalblue', width=2)
))

# Google Trends (right axis)
fig.add_trace(go.Scatter(
    x=zoom['observation_date'],
    y=zoom['AI_Searches'],
    name='Google Trends: "AI"',
    line=dict(color='orange', width=3, dash='dot'),
    yaxis='y2'
))

fig.update_layout(
    title={
        "text": "Bitcoin vs Google Trends for 'AI' Searches (2022–2026)",
        "x": 0.5
    },
    xaxis=dict(title="Date"),
    yaxis=dict(title="Bitcoin Price (USD)"),
    yaxis2=dict(
        title="Google Trends: 'AI'",
        overlaying='y',
        side='right'
    ),
    template="plotly_white",
    legend=dict(x=0.02, y=0.98),
    margin=dict(l=60, r=60, t=80, b=40)
)

fig.show()

df_ai[['observation_date', 'AI_Searches']].head(20)

df_ai[df_ai['observation_date'] >= '2022-01-01'].head(20)

df_ai['observation_date'] = pd.to_datetime(df_ai['observation_date'])
gt['observation_date'] = pd.to_datetime(gt['observation_date'])

df_ai = pd.merge(
    df,
    gt,
    on='observation_date',
    how='left'
)

zoom = df_ai[
    (df_ai['observation_date'] >= "2022-01-01") &
    (df_ai['observation_date'] <= "2026-12-31")
]

import plotly.graph_objects as go

fig = go.Figure()

# Bitcoin (left axis)
fig.add_trace(go.Scatter(
    x=zoom['observation_date'],
    y=zoom['CBBTCUSD'],
    name='Bitcoin Price (USD)',
    line=dict(color='royalblue', width=2)
))

# Google Trends (right axis)
fig.add_trace(go.Scatter(
    x=zoom['observation_date'],
    y=zoom['AI_Searches'],
    name='Google Trends: "AI"',
    line=dict(color='orange', width=3, dash='dot'),
    yaxis='y2'
))

fig.update_layout(
    title={
        "text": "Bitcoin vs Google Trends for 'AI' Searches (2022–2026)",
        "x": 0.5
    },
    xaxis=dict(title="Date"),
    yaxis=dict(title="Bitcoin Price (USD)"),
    yaxis2=dict(
        title="Google Trends: 'AI'",
        overlaying='y',
        side='right'
    ),
    template="plotly_white",
    legend=dict(x=0.02, y=0.98),
    margin=dict(l=60, r=60, t=80, b=40)
)

fig.show()

df_ai[df_ai['observation_date'] >= '2022-01-01'].head(20)

df_ai['AI_Searches'] = df_ai['AI_Searches'].ffill()

zoom = df_ai[
    (df_ai['observation_date'] >= "2022-01-01") &
    (df_ai['observation_date'] <= "2026-12-31")
]

import plotly.graph_objects as go

fig = go.Figure()

# Bitcoin (left axis)
fig.add_trace(go.Scatter(
    x=zoom['observation_date'],
    y=zoom['CBBTCUSD'],
    name='Bitcoin Price (USD)',
    line=dict(color='royalblue', width=2)
))

# Google Trends (right axis)
fig.add_trace(go.Scatter(
    x=zoom['observation_date'],
    y=zoom['AI_Searches'],
    name='Google Trends: "AI"',
    line=dict(color='orange', width=3, dash='dot'),
    yaxis='y2'
))

fig.update_layout(
    title={
        "text": "Bitcoin vs Google Trends for 'AI' Searches (2022–2026)",
        "x": 0.5
    },
    xaxis=dict(title="Date"),
    yaxis=dict(title="Bitcoin Price (USD)"),
    yaxis2=dict(
        title="Google Trends: 'AI'",
        overlaying='y',
        side='right'
    ),
    template="plotly_white",
    legend=dict(x=0.02, y=0.98),
    margin=dict(l=60, r=60, t=80, b=40)
)

fig.show()

# Google Trends (right axis) — solid line
fig.add_trace(go.Scatter(
    x=zoom['observation_date'],
    y=zoom['AI_Searches'],
    name='Google Trends: "AI"',
    line=dict(color='orange', width=3),  # removed dash='dot'
    yaxis='y2'
))

line=dict(color='orange', width=2, shape='spline')

import plotly.graph_objects as go

fig = go.Figure()

# -----------------------------
# Bitcoin (left axis)
# -----------------------------
fig.add_trace(go.Scatter(
    x=zoom['observation_date'],
    y=zoom['CBBTCUSD'],
    name='Bitcoin Price (USD)',
    line=dict(color='#1f77b4', width=2)  # Bloomberg blue
))

# -----------------------------
# Google Trends (right axis)
# -----------------------------
fig.add_trace(go.Scatter(
    x=zoom['observation_date'],
    y=zoom['AI_Searches'],
    name='Google Trends: "AI"',
    line=dict(color='#ff7f0e', width=2),  # solid orange line
    yaxis='y2'
))

# -----------------------------
# Layout (Bloomberg style)
# -----------------------------
fig.update_layout(
    title={
        "text": "Bitcoin vs Google Trends for 'AI' Searches (2022–2026)",
        "x": 0.5
    },
    xaxis=dict(
        title="Date",
        gridcolor="#333333",
        zerolinecolor="#333333"
    ),
    yaxis=dict(
        title="Bitcoin Price (USD)",
        gridcolor="#333333",
        zerolinecolor="#333333"
    ),
    yaxis2=dict(
        title="Google Trends: 'AI'",
        overlaying='y',
        side='right',
        gridcolor="#333333",
        zerolinecolor="#333333"
    ),
    template="plotly_dark",
    font=dict(family="Arial", size=12, color="white"),
    plot_bgcolor="#111111",
    paper_bgcolor="#111111",
    legend=dict(x=0.02, y=0.98),
    margin=dict(l=60, r=60, t=80, b=40)
)

fig.show()

truf.head()

truf = pd.read_csv("truflation.csv")

truf = pd.read_excel("truflation.xlsx")

import os

for root, dirs, files in os.walk('/'):
    for f in files:
        name = f.lower()
        if 'truf' in name or 'inflation' in name:
            print(os.path.join(root, f))

from google.colab import files
uploaded = files.upload()

import pandas as pd

url = "https://raw.githubusercontent.com/truflation/data/main/us_truflation_index.csv"
truf = pd.read_csv(url)

import pandas as pd

# Search the Truflation GitHub repo for CSV files
search_url = "https://api.github.com/repos/truflation/data/contents"
contents = pd.read_json(search_url)

contents

import pandas as pd

url = "https://raw.githubusercontent.com/itsdanielj/cpi-daily/main/data/cpi_daily.csv"
infl = pd.read_csv(url)

!pip install fredapi
from fredapi import Fred

fred = Fred()

import pandas as pd

url = "https://api.alternative.me/fng/?limit=0&format=csv"
fng = pd.read_csv(url)

import pandas as pd

url = "https://raw.githubusercontent.com/justinmahar/crypto-fear-and-greed/master/data/fng.csv"
fng = pd.read_csv(url)

import pandas as pd
import requests

url = "https://api.alternative.me/fng/?limit=0"
data = requests.get(url).json()

fng = pd.DataFrame(data['data'])

fng.columns = fng.columns.str.lower()

fng = fng.rename(columns={
    'timestamp': 'observation_date',
    'value': 'fear_greed'
})

fng['observation_date'] = pd.to_datetime(fng['observation_date'], unit='s')
fng['fear_greed'] = pd.to_numeric(fng['fear_greed'])

fng = fng.sort_values('observation_date').reset_index(drop=True)

fng.head()

# Daily change
fng['delta'] = fng['fear_greed'].diff()

# Gains and losses
fng['gain'] = fng['delta'].clip(lower=0)
fng['loss'] = (-fng['delta']).clip(lower=0)

# RSI-style smoothing
n = 14
fng['avg_gain'] = fng['gain'].ewm(alpha=1/n, min_periods=n).mean()
fng['avg_loss'] = fng['loss'].ewm(alpha=1/n, min_periods=n).mean()

# RS
fng['rs'] = fng['avg_gain'] / fng['avg_loss']

# FG-RSI
fng['fg_rsi'] = 100 - (100 / (1 + fng['rs']))

fg_rsi = fng[['observation_date', 'fear_greed', 'fg_rsi']]

fg_rsi.head()

fg_rsi.tail()

import plotly.graph_objects as go

fig = go.Figure()

# -----------------------------
# FG‑RSI line
# -----------------------------
fig.add_trace(go.Scatter(
    x=fg_rsi['observation_date'],
    y=fg_rsi['fg_rsi'],
    name='FG‑RSI',
    line=dict(color='#1f77b4', width=2)
))

# -----------------------------
# Overbought / Oversold zones
# -----------------------------
fig.add_hline(y=70, line=dict(color='red', width=1, dash='dash'))
fig.add_hline(y=30, line=dict(color='green', width=1, dash='dash'))

# -----------------------------
# Layout (Bloomberg style)
# -----------------------------
fig.update_layout(
    title={
        "text": "Bitcoin Fear & Greed RSI (FG‑RSI)",
        "x": 0.5
    },
    xaxis=dict(
        title="Date",
        gridcolor="#333333",
        zerolinecolor="#333333"
    ),
    yaxis=dict(
        title="FG‑RSI (0–100)",
        range=[0, 100],
        gridcolor="#333333",
        zerolinecolor="#333333"
    ),
    template="plotly_dark",
    font=dict(family="Arial", size=12, color="white"),
    plot_bgcolor="#111111",
    paper_bgcolor="#111111",
    margin=dict(l=60, r=60, t=80, b=40),
    showlegend=False
)

fig.show()

fig.add_trace(go.Scatter(
    x=fg_rsi['observation_date'],
    y=fg_rsi['fg_rsi'],
    name='FG‑RSI',
    line=dict(color='#1f77b4', width=1)   # thinner line
))

import plotly.graph_objects as go

fig = go.Figure()

# -----------------------------
# FG‑RSI line (thin)
# -----------------------------
fig.add_trace(go.Scatter(
    x=fg_rsi['observation_date'],
    y=fg_rsi['fg_rsi'],
    name='FG‑RSI',
    line=dict(color='#1f77b4', width=1)
))

# -----------------------------
# Overbought / Oversold zones
# -----------------------------
fig.add_hline(y=70, line=dict(color='red', width=1, dash='dash'))
fig.add_hline(y=30, line=dict(color='green', width=1, dash='dash'))

# -----------------------------
# Layout (Bloomberg style)
# -----------------------------
fig.update_layout(
    title={
        "text": "Bitcoin Fear & Greed RSI (FG‑RSI)",
        "x": 0.5
    },
    xaxis=dict(
        title="Date",
        gridcolor="#333333",
        zerolinecolor="#333333"
    ),
    yaxis=dict(
        title="FG‑RSI (0–100)",
        range=[0, 100],
        gridcolor="#333333",
        zerolinecolor="#333333"
    ),
    template="plotly_dark",
    font=dict(family="Arial", size=12, color="white"),
    plot_bgcolor="#111111",
    paper_bgcolor="#111111",
    margin=dict(l=60, r=60, t=80, b=40),
    showlegend=False
)

fig.show()

import pickle

with open("fg_rsi_chart.pkl", "wb") as f:
    pickle.dump(fig, f)

fig.write_html("fg_rsi_chart.html")

fig.write_html("fg_rsi.html", include_plotlyjs="cdn", full_html=True)

fig.write_html("fg_rsi.html", include_plotlyjs="cdn", full_html=False)

from google.colab import files
files.download("fg_rsi.html")

# MacroPulseWeekly Theme

import plotly.io as pio

macro_theme = {
    "layout": {
        "paper_bgcolor": "#111111",
        "plot_bgcolor": "#111111",
        "font": {"family": "Arial", "color": "#FFFFFF", "size": 14},
        "title": {"font": {"size": 26, "color": "#FFFFFF"}, "x": 0.05},
        "xaxis": {
            "gridcolor": "#333333",
            "zerolinecolor": "#333333",
            "showgrid": True,
            "showline": False,
        },
        "yaxis": {
            "gridcolor": "#333333",
            "zerolinecolor": "#333333",
            "showgrid": True,
            "showline": False,
        },
        "legend": {
            "orientation": "h",
            "yanchor": "bottom",
            "y": 1.02,
            "xanchor": "right",
            "x": 1,
            "font": {"size": 12, "color": "#FFFFFF"},
        },
        "margin": {"l": 60, "r": 40, "t": 80, "b": 40},
    }
}

pio.templates["macro_pulse"] = macro_theme
pio.templates.default = "macro_pulse"

mpw_blue = "#4DA3FF"
mpw_orange = "#FF8C42"
mpw_green = "#4CAF50"
mpw_red = "#FF5252"
mpw_yellow = "#FFC857"
mpw_gray = "#888888"

fig.add_trace(go.Scatter(
    x=df.index,
    y=df["value"],
    name="FG-RSI",
    line=dict(color=mpw_blue, width=3)
))

fig.add_trace(go.Scatter(
    x=df_fgrsi.index,
    y=df_fgrsi["FG_RSI"],
    name="FG-RSI",
    line=dict(color=mpw_blue, width=3)
))

fig.add_trace(go.Scatter(
    x=df_fgrsi.index,
    y=df_fgrsi["FG-RSI"],
    name="FG-RSI",
    line=dict(color=mpw_blue, width=3)
))

import plotly.graph_objects as go
import plotly.io as pio

# ================================
# MacroPulseWeekly Chart Theme
# ================================

# Brand color palette
mpw_blue   = "#4DA3FF"
mpw_orange = "#FF8C42"
mpw_green  = "#4CAF50"
mpw_red    = "#FF5252"
mpw_yellow = "#FFC857"
mpw_gray   = "#888888"

macro_theme = {
    "layout": {
        "paper_bgcolor": "#111111",
        "plot_bgcolor": "#111111",
        "font": {"family": "Arial", "color": "#FFFFFF", "size": 14},

        "title": {
            "font": {"size": 26, "color": "#FFFFFF"},
            "x": 0.05
        },

        "xaxis": {
            "gridcolor": "#333333",
            "zerolinecolor": "#333333",
            "showgrid": True,
            "showline": False,
        },

        "yaxis": {
            "gridcolor": "#333333",
            "zerolinecolor": "#333333",
            "showgrid": True,
            "showline": False,
        },

        "legend": {
            "orientation": "h",
            "yanchor": "bottom",
            "y": 1.02,
            "xanchor": "right",
            "x": 1,
            "font": {"size": 12, "color": "#FFFFFF"},
        },

        "margin": {"l": 60, "r": 40, "t": 80, "b": 40},
    }
}

# Register + activate theme
pio.templates["macro_pulse"] = macro_theme
pio.templates.default = "macro_pulse"

import plotly.graph_objects as go
import plotly.io as pio

# ================================
# MacroPulseWeekly Chart Theme
# ================================

# Brand color palette
mpw_blue   = "#4DA3FF"
mpw_orange = "#FF8C42"
mpw_green  = "#4CAF50"
mpw_red    = "#FF5252"
mpw_yellow = "#FFC857"
mpw_gray   = "#888888"

macro_theme = {
    "layout": {
        "paper_bgcolor": "#111111",
        "plot_bgcolor": "#111111",
        "font": {"family": "Arial", "color": "#FFFFFF", "size": 14},

        "title": {
            "font": {"size": 26, "color": "#FFFFFF"},
            "x": 0.05
        },

        "xaxis": {
            "gridcolor": "#333333",
            "zerolinecolor": "#333333",
            "showgrid": True,
            "showline": False,
        },

        "yaxis": {
            "gridcolor": "#333333",
            "zerolinecolor": "#333333",
            "showgrid": True,
            "showline": False,
        },

        "legend": {
            "orientation": "h",
            "yanchor": "bottom",
            "y": 1.02,
            "xanchor": "right",
            "x": 1,
            "font": {"size": 12, "color": "#FFFFFF"},
        },

        "margin": {"l": 60, "r": 40, "t": 80, "b": 40},
    }
}

# Register + activate theme
pio.templates["macro_pulse"] = macro_theme
pio.templates.default = "macro_pulse"

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=fg_rsi.index,
    y=fg_rsi["fg_rsi"],
    name="FG-RSI",
    line=dict(color=mpw_blue, width=3)
))

fig.update_layout(
    title="Bitcoin Fear & Greed RSI<br><span style='font-size:14px; color:#AAAAAA;'>MacroPulseWeekly</span>"
)

fig.show()

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=fig_rsi.index,
    y=fig_rsi["FG_RSI"],   # or whatever your column is called
    name="FG-RSI",
    line=dict(color=mpw_blue, width=3)
))

fig.update_layout(
    title="Bitcoin Fear & Greed RSI<br><span style='font-size:14px; color:#AAAAAA;'>MacroPulseWeekly</span>"
)

fig.show()

fig_rsi.columns

fg_rsi.columns

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=fg_rsi.index,
    y=fg_rsi["fg_rsi"],   # Corrected column name to 'fg_rsi'
    name="FG-RSI",
    line=dict(color=mpw_blue, width=3)
))

fig.update_layout(
    title="Bitcoin Fear & Greed RSI<br><span style='font-size:14px; color:#AAAAAA;'>MacroPulseWeekly</span>"
)

fig.show()

fig = go.Figure()

# -----------------------------
# Main FG-RSI line (thinner)
# -----------------------------
fig.add_trace(go.Scatter(
    x=fg_rsi.index,
    y=fg_rsi["FG_RSI"],
    name="FG-RSI",
    line=dict(color=mpw_blue, width=2)   # thinner line
))

# -----------------------------
# RSI guide lines (70 and 30)
# -----------------------------
fig.add_hline(
    y=70,
    line=dict(color=mpw_red, width=1, dash="dash"),
    annotation_text="70",
    annotation_position="top left",
    annotation_font_color="#AAAAAA"
)

fig.add_hline(
    y=30,
    line=dict(color=mpw_green, width=1, dash="dash"),
    annotation_text="30",
    annotation_position="bottom left",
    annotation_font_color="#AAAAAA"
)

# -----------------------------
# Title + subtitle
# -----------------------------
fig.update_layout(
    title="Bitcoin Fear & Greed RSI<br><span style='font-size:14px; color:#AAAAAA;'>MacroPulseWeekly</span>"
)

fig.show()

fig = go.Figure()

# -----------------------------
# Main FG-RSI line (thinner)
# -----------------------------
fig.add_trace(go.Scatter(
    x=fg_rsi.index,
    y=fg_rsi["fg_rsi"],   # <-- corrected column name
    name="FG-RSI",
    line=dict(color=mpw_blue, width=2)   # thinner line
))

# -----------------------------
# RSI guide lines (70 and 30)
# -----------------------------
fig.add_hline(
    y=70,
    line=dict(color=mpw_red, width=1, dash="dash"),
    annotation_text="70",
    annotation_position="top left",
    annotation_font_color="#AAAAAA"
)

fig.add_hline(
    y=30,
    line=dict(color=mpw_green, width=1, dash="dash"),
    annotation_text="30",
    annotation_position="bottom left",
    annotation_font_color="#AAAAAA"
)

# -----------------------------
# Title + subtitle
# -----------------------------
fig.update_layout(
    title="Bitcoin Fear & Greed RSI<br><span style='font-size:14px; color:#AAAAAA;'>MacroPulseWeekly</span>"
)

fig.show()

fig = go.Figure()

# -----------------------------
# Main FG-RSI line (even thinner)
# -----------------------------
fig.add_trace(go.Scatter(
    x=fg_rsi.index,
    y=fg_rsi["fg_rsi"],   # correct column
    name="FG-RSI",
    line=dict(color=mpw_blue, width=1.2)   # thinner line
))

# -----------------------------
# RSI guide lines (70 and 30)
# -----------------------------
fig.add_hline(
    y=70,
    line=dict(color=mpw_red, width=1, dash="dash"),
    annotation_text="70",
    annotation_position="top left",
    annotation_font_color="#AAAAAA"
)

fig.add_hline(
    y=30,
    line=dict(color=mpw_green, width=1, dash="dash"),
    annotation_text="30",
    annotation_position="bottom left",
    annotation_font_color="#AAAAAA"
)

# -----------------------------
# Title + subtitle
# -----------------------------
fig.update_layout(
    title="Bitcoin Fear & Greed RSI<br><span style='font-size:14px; color:#AAAAAA;'>MacroPulseWeekly</span>"
)

fig.show()

fig = go.Figure()

# -----------------------------
# Main FG-RSI line (even thinner)
# -----------------------------
fig.add_trace(go.Scatter(
    x=fg_rsi.index,
    y=fg_rsi["fg_rsi"],   # correct column
    name="FG-RSI",
    line=dict(color=mpw_blue, width=1)   # even thinner
))

# -----------------------------
# RSI guide lines (70 and 30)
# -----------------------------
fig.add_hline(
    y=70,
    line=dict(color=mpw_red, width=1, dash="dash"),
    annotation_text="70",
    annotation_position="top left",
    annotation_font_color="#AAAAAA"
)

fig.add_hline(
    y=30,
    line=dict(color=mpw_green, width=1, dash="dash"),
    annotation_text="30",
    annotation_position="bottom left",
    annotation_font_color="#AAAAAA"
)

# -----------------------------
# Force x-axis dates to show
# -----------------------------
fig.update_xaxes(
    showgrid=True,
    tickformat="%Y-%m-%d",
    ticks="outside",
    tickfont=dict(size=12, color="#AAAAAA"),
    showticklabels=True
)

# -----------------------------
# Title + subtitle
# -----------------------------
fig.update_layout(
    title="Bitcoin Fear & Greed RSI<br><span style='font-size:14px; color:#AAAAAA;'>MacroPulseWeekly</span>"
)

fig.show()

fg_rsi.index

fg_rsi.columns

fg_rsi["observation_date"] = pd.to_datetime(fg_rsi["observation_date"])

fg_rsi = fg_rsi.set_index("observation_date")

fig = go.Figure()

# Main FG-RSI line (thin)
fig.add_trace(go.Scatter(
    x=fg_rsi.index,
    y=fg_rsi["fg_rsi"],
    name="FG-RSI",
    line=dict(color=mpw_blue, width=1)
))

# RSI guide lines
fig.add_hline(
    y=70,
    line=dict(color=mpw_red, width=1, dash="dash"),
    annotation_text="70",
    annotation_position="top left",
    annotation_font_color="#AAAAAA"
)

fig.add_hline(
    y=30,
    line=dict(color=mpw_green, width=1, dash="dash"),
    annotation_text="30",
    annotation_position="bottom left",
    annotation_font_color="#AAAAAA"
)

# Force date labels
fig.update_xaxes(
    tickformat="%Y-%m-%d",
    showticklabels=True,
    tickfont=dict(size=12, color="#AAAAAA")
)

# Title
fig.update_layout(
    title="Bitcoin Fear & Greed RSI<br><span style='font-size:14px; color:#AAAAAA;'>MacroPulseWeekly</span>"
)

fig.show()

fig.write_html("fg_rsi.html", include_plotlyjs="cdn", full_html=False)

fig.write_html("fg_rsi.html", include_plotlyjs="cdn", full_html=False)

from google.colab import files
files.download("fg_rsi.html")

fig.update_layout(
    title=dict(
        text="Bitcoin Fear & Greed RSI<br><span style='font-size:14px; color:#AAAAAA;'>MacroPulseWeekly</span>",
        x=0.5,  # center the title
        xanchor="center"
    )
)

fig.update_yaxes(range=[0, 100])

fig = go.Figure()

# Main FG-RSI line (thin)
fig.add_trace(go.Scatter(
    x=fg_rsi.index,
    y=fg_rsi["fg_rsi"],
    name="FG-RSI",
    line=dict(color=mpw_blue, width=1)
))

# RSI guide lines
fig.add_hline(
    y=70,
    line=dict(color=mpw_red, width=1, dash="dash"),
    annotation_text="70",
    annotation_position="top left",
    annotation_font_color="#AAAAAA"
)

fig.add_hline(
    y=30,
    line=dict(color=mpw_green, width=1, dash="dash"),
    annotation_text="30",
    annotation_position="bottom left",
    annotation_font_color="#AAAAAA"
)

# Force date labels
fig.update_xaxes(
    tickformat="%Y-%m-%d",
    showticklabels=True,
    tickfont=dict(size=12, color="#AAAAAA")
)

# Fix y-axis scale to 0–100
fig.update_yaxes(range=[0, 100])

# Centered title
fig.update_layout(
    title=dict(
        text="Bitcoin Fear & Greed RSI<br><span style='font-size:14px; color:#AAAAAA;'>MacroPulseWeekly</span>",
        x=0.5,
        xanchor="center"
    )
)

fig.show()

# Export updated chart
fig.write_html("fg_rsi.html", include_plotlyjs="cdn", full_html=False)

# Force download to your computer
from google.colab import files
files.download("fg_rsi.html")

import plotly.graph_objects as go
import plotly.io as pio

# ============================================
# MacroPulseWeekly Global Chart Theme
# ============================================

# Brand color palette
mpw_blue   = "#4DA3FF"
mpw_orange = "#FF8C42"
mpw_green  = "#4CAF50"
mpw_red    = "#FF5252"
mpw_yellow = "#FFC857"
mpw_gray   = "#888888"

macro_theme = {
    "layout": {
        # Backgrounds
        "paper_bgcolor": "#111111",
        "plot_bgcolor": "#111111",

        # Global font
        "font": {"family": "Arial", "color": "#FFFFFF", "size": 14},

        # Centered title style
        "title": {
            "font": {"size": 26, "color": "#FFFFFF"},
            "x": 0.5,
            "xanchor": "center"
        },

        # X-axis styling
        "xaxis": {
            "gridcolor": "#333333",
            "zerolinecolor": "#333333",
            "showgrid": True,
            "showline": False,
            "tickfont": {"size": 12, "color": "#AAAAAA"},
        },

        # Y-axis styling
        "yaxis": {
            "gridcolor": "#333333",
            "zerolinecolor": "#333333",
            "showgrid": True,
            "showline": False,
            "tickfont": {"size": 12, "color": "#AAAAAA"},
        },

        # Legend styling
        "legend": {
            "orientation": "h",
            "yanchor": "bottom",
            "y": 1.02,
            "xanchor": "right",
            "x": 1,
            "font": {"size": 12, "color": "#FFFFFF"},
        },

        # Margins
        "margin": {"l": 60, "r": 40, "t": 80, "b": 40},
    }
}

# Register + activate theme
pio.templates["macro_pulse"] = macro_theme
pio.templates.default = "macro_pulse"

df_ai["observation_date"] = pd.to_datetime(df_ai["observation_date"])
df_ai = df_ai.set_index("observation_date")

fig = go.Figure()

# Bitcoin price (left axis)
fig.add_trace(go.Scatter(
    x=df_ai.index,
    y=df_ai["CBBTCUSD"],
    name="Bitcoin Price",
    line=dict(color=mpw_blue, width=2)
))

# Google AI Trends (right axis)
fig.add_trace(go.Scatter(
    x=df_ai.index,
    y=df_ai["AI_Searches"],
    name="Google AI Trend",
    line=dict(color=mpw_orange, width=2),
    yaxis="y2"
))

# Dual-axis layout
fig.update_layout(
    title="Bitcoin vs Google AI Trends<br><span style='font-size:14px; color:#AAAAAA;'>MacroPulseWeekly</span>",
    yaxis=dict(title="BTC Price (USD)"),
    yaxis2=dict(
        title="Google AI Search Interest",
        overlaying="y",
        side="right"
    )
)

# Date formatting
fig.update_xaxes(
    tickformat="%Y-%m-%d",
    showticklabels=True
)

fig.show()

# Ensure datetime index
# Replaced 'btc_trends' with 'df_ai'
# Replaced 'btc_price' with 'CBBTCUSD'
# Replaced 'google_ai_trend' with 'AI_Searches'

# Filter to start at 2022
btc_trends_2022 = df_ai.loc["2022":]

fig = go.Figure()

# Bitcoin price (left axis) — thinner line
fig.add_trace(go.Scatter(
    x=btc_trends_2022.index,
    y=btc_trends_2022["CBBTCUSD"],
    name="Bitcoin Price",
    line=dict(color=mpw_blue, width=1.5)
))

# Google AI Trends (right axis) — thinner line
fig.add_trace(go.Scatter(
    x=btc_trends_2022.index,
    y=btc_trends_2022["AI_Searches"],
    name="Google AI Trend",
    line=dict(color=mpw_orange, width=1.5),
    yaxis="y2"
))

# Dual-axis layout
fig.update_layout(
    title="Bitcoin vs Google AI Trends<br><span style='font-size:14px; color:#AAAAAA;'>MacroPulseWeekly</span>",
    yaxis=dict(title="BTC Price (USD)"),
    yaxis2=dict(
        title="Google AI Search Interest",
        overlaying="y",
        side="right"
    )
)

# Date formatting
fig.update_xaxes(
    tickformat="%Y-%m-%d",
    showticklabels=True
)

fig.show()

fig.write_html("btc_vs_google_ai.html", include_plotlyjs="cdn", full_html=False)

from google.colab import files
files.download("btc_vs_google_ai.html")

!pip install yfinance pandas matplotlib

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

# Download BTC data
btc = yf.download("BTC-USD", start="2014-01-01")

# Convert to monthly
btc_monthly = btc["Close"].resample("M").last()

